theme: jekyll-theme-hacker

#paginate: 10
#plugins: [jekyll-paginate]
#paginate_path: "blog/:num/"

title: MCH2022Telex
description: Output of the @MCH2022Telex project

timezone: Europe/Amsterdam
future: true
encoding: utf-8

permalink: pretty
markdown: kramdown
show_downloads: true
github:
  is_project_page: true

plugins:
  - jekyll-sitemap

repository: mrseccubus/mchtelex

collections:
  sheets:
    output: true
  posts:
    output: false

exclude:
  - serve
  - Gemfile
  - Gemfile.lock
