#!/bin/bash


if [[ ! -z $1 ]]; then
	PORT=$1
else
	PORT=4000
fi

docker pull mrseccubus/github-pages:latest
if [[ $(uname -a|grep -i microsoft|wc -l) -gt 0 ]]; then
	IP=$(ip addr show eth0 |grep "inet "|awk '{ print $2 }'|sed 's/\/.*$//')
	echo "*******************************************************************************************"
	echo "On WSL2 the docker container is reachable via this url: http://$IP:$PORT"
	echo "*******************************************************************************************"
	echo "webrick:
  headers:" > _config_livereload.yml
	grep Content-Security-Policy _config.yml | \
		sed "s#script-src #script-src 'sha256-ehJx3nUTxQSjcKzJh47dVVjmxNcjTJlcgIuP/LP035Y=' http://$IP:35729 #" |\
		sed "s#connect-src #connect-src * #" \
		>> _config_livereload.yml
else
	echo "webrick:
  headers:" > _config_livereload.yml
  	grep Content-Security-Policy _config.yml | \
  	sed "s#script-src #script-src * #" | \
  	sed "s#connect-src #connect-src * #" \
  	>> _config_livereload.yml
fi
if [[ $( grep headers _config.yml | wc -l ) -ne 0 ]]; then
	LIVERELOADCONFIG=",_config_livereload.yml"
fi
docker run \
	--volume="$PWD:/root/project:delegated" \
	--entrypoint /bin/bash \
	--publish $PORT:4000 \
	--publish 35729:35729 \
	-ti mrseccubus/github-pages \
	-c "
		set -x
		cd /root/project/;
		if [[ -e Gemfile ]]; then
			echo \"*** Installing Gems in Gemfile ***\"
			bundle install 
			EXEC=\"bundle exec\"
		fi

		while [ 1 ] ; do
			rm -rf _site/* _site/.*;
			\$EXEC jekyll serve --incremental --watch --livereload --force-polling --host=0.0.0.0 --future --config=_config.yml$LIVERELOADCONFIG 2>&1
			set -e
			echo 'Press CTRL+C now to quit'
			sleep 1
			set +e
			echo 'Restarting...'
		done
	"